### ISSUE TITLE
Parse hex color

### ISSUE THREAD

**Issue by g4s8** [g4s8/hexcolor#1]
Parse hex color to get `Color` from `image/color`.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#2](https://github.com/g4s8/hexcolor/issues/2) is still not solved.

**Comment by g4s8** [comment]
done

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#2](https://github.com/g4s8/hexcolor/issues/2) is solved here.
