### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by g4s8** [g4s8/hexcolor#5]
Add package docs, `Parse()` func docs, godocs badge and reference to readme.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#6](https://github.com/g4s8/hexcolor/issues/6) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#6](https://github.com/g4s8/hexcolor/issues/6) is solved here.
